CREATE TABLE TBL_AUTHOR (
    AUTHOR_ID INT PRIMARY KEY,
    AUTHOR_NAME VARCHAR(50),
    AUTHOR_COUNTRY VARCHAR(50)
);

CREATE TABLE TBL_BOOK (
    BOOK_ID INT PRIMARY KEY,
    BOOK_TITLE VARCHAR(50),
    AUTHOR_ID INT,
    FOREIGN KEY (AUTHOR_ID) REFERENCES TBL_AUTHOR(AUTHOR_ID)
);

INSERT INTO TBL_AUTHOR (AUTHOR_ID, AUTHOR_NAME, AUTHOR_COUNTRY) VALUES
(1, 'C.J. Date', 'USA'),
(2, 'Silberschatz', 'Germany'),
(3, 'A. Tanenbaum', 'Netherlands');

INSERT INTO TBL_BOOK (BOOK_ID, BOOK_TITLE, AUTHOR_ID) VALUES
(101, 'Database Systems Concepts', 2),
(102, 'Modern Operating Systems', 3),
(103, 'An Introduction to Database Systems', 1),
(104, 'Computer Architecture', 3),
(105, 'Advanced Database Techniques', 1);

SELECT 
    B.BOOK_TITLE, 
    A.AUTHOR_NAME, 
    A.AUTHOR_COUNTRY
FROM 
    TBL_BOOK AS B
INNER JOIN 
    TBL_AUTHOR AS A
ON 
    B.AUTHOR_ID = A.AUTHOR_ID;
